version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: rvm install 2.4 && echo . $(rvm 2.4 do rvm env --path) >> $BASH_ENV
      - run: cd docs && gem install bundler && bundle install && bundle exec jekyll algolia
      - run: npm install
      - run: npm link && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: fliplet env staging
      - run: fliplet login -u $TEST_USER -p $TEST_PASSWORD
      - run: fliplet organization $TEST_ORGANIZATION
      - run: fliplet create-widget awesome-widget
      - run: cd awesome-widget && fliplet test
  publish:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm link && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build