url: https://developers.fliplet.com

plugins:
  - jekyll-sitemap

include:
  - _headers
  - .well-known

exclude:
  - docsearch
  - bin
  - test
  - templates
  - Gemfile
  - Gemfile.lock

algolia:
  application_id: '8GRBFEV21Y'
